version: "3"

services:
  web:
    image: node:16
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    restart: unless-stopped
    user: root
    ports:
      - 3000:3000
    network_mode: host